### ISSUE TITLE
Zip files from glob of content

### ISSUE THREAD

**Issue by chandresh-pancholi** [oneconcern/datamon#11]
**Issue:** 
The input file has a content array of globs. we need to zip all the files and directory.

``datamon deploy function --from-file <example.yaml>``

Steps

- Datamon reads content from example.yaml & zip all the files from content attribute in example.yaml

-  example of glob of content from example.yaml
```
content:
  - vendor/*
  - scripts/*
  - bin/*
  - requirements.txt
  - app.py
```

**Success Criteria**

- Successfully able to zip all the given globs

- Unit tests 

-  Corner cases like 0 files check

- Proper logging statements, Successfully uploaded & failed uploaded files prometheus custom metrics

**Comment by kerneltime** [comment]
not relevant any more
