### ISSUE TITLE
Create kubeless function & deploy it on Kubernetes

### ISSUE THREAD

**Issue by chandresh-pancholi** [oneconcern/datamon#13]
**Issue**
Using the [config file](https://github.com/oneconcern/datamon/issues/1), generate Kubeless Function Object and use it to create [Function CRD](https://github.com/kubeless/kubeless/blob/master/docs/architecture.md) in Kubernetes.

**Success Criteria**

- Kubeless function deployment on Kubernetes

- Unit test for SHA-256/File SHA-256, content type, Kubeless function,

- Prometheus metrics

**Comment by kerneltime** [comment]
Not relevant any more
