### ISSUE TITLE
daemonize mount command

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#138]
by default, the `bundle mount` command ought to run a [daemonized](https://github.com/jacobsa/daemonize/blob/master/daemonize.go) process similar to [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse).

unmounting the bundle ought to cause the process to exit.

further impedance matching with gcsfuse [suggests](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mounting) that adding a `--foreground` flag to disable daemonization is desirable.

**Comment by ransomw1c** [comment]
the main differences between daemonizing and running as a background process are:

* the process runs in a different process group and thus doesn't get signals sent to the terminal
* the process's stdio are disconnected from the terminal

so in particular, when running as a daemonized process, logs need be written to a file

**Comment by kerneltime** [comment]
@kerneltime to finish up the code review.

**Comment by ransomw1c** [comment]
[need to toggle switch semantics](https://github.com/oneconcern/datamon/pull/140#discussion_r286661734).

**Comment by fredbi** [comment]
mount as a deamon is now supported and allegedly, works fine. Closing this now.
