### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by chandresh-pancholi** [oneconcern/datamon#139]
Ritesh/Ivan,

I would like to contribute to this project. I couldn't find developer contribution guide. It would be great if you can share one. Also, I saw one PR related to CSI, I would be happy to work on it.

Waiting for your response.

Thanks

**Comment by kerneltime** [comment]
@chandresh-pancholi let me know what additional information do you seek to what is already posted here https://github.com/oneconcern/datamon/blob/master/CONTRIBUTING.md
We are testing out the GKE CSI integration and will merge in the work soon. Any help is always welcome once the CSI framework is in.

**Comment by chandresh-pancholi** [comment]
Thanks @kerneltime. Looking forward to make contribution to the project.
