### ISSUE TITLE
Custom runtime to execute functions

### ISSUE THREAD

**Issue by chandresh-pancholi** [oneconcern/datamon#15]
The developers can get the help of the operation team to create custom runtime to run their functions.
MVP is going to use default Kubeless runtimes

Supported Runtimes are:

> **python2.7, python3.4, python3.6, nodejs6, nodejs8, ruby2.4, php7.2, go1.10, dotnetcore2.0, java1.8, ballerina0.981.0**

**Comment by kerneltime** [comment]
Not applicable any more
