### ISSUE TITLE
Caching CAFS for RO FS Fuse mount

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#158]
When a RO fuse FS is mounted, if the flag is set, the FS is made available as soon as the metadata is ready. A CAFS local cache storage is used to pass in pre downloaded blobs. Any misses in the CAFS cache result in it being fetched from the the backend before serving the read. 

An additional optimization is to only download the chunk which serves the read boundary.

**Comment by ransomw1c** [comment]
from #162 , it emerges that having a `storage.Store` that uses local storage and does atomic writes via `mv` will be useful toward this iss.

**Comment by fredbi** [comment]
Update: blob cache and prefetching work fine. Closing this now.
