### ISSUE TITLE
CLI flag spec deduplication

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#165]
whether we use [`cobra`-specific design patterns](https://github.com/spf13/cobra#local-flag-on-parent-commands) or a more bespoke implementation such as the existing

```
requiredFlags := []string{...
for ... range requiredFlags {...
```

idiom, there's probably some way to structure the way the UI is specified as go code. 

specifically, there are some parallels between the way cobra commands are structured and the flags that correspond to those commands.  so in particular, if we'd like to add a `--profile` flag to every command that guards the `*CpuProf` flags added in b6149c9, the way things are currently structured, it'd probably be most consistent to create an `addProfileFlag` function in `cmd/root.go` and then call that in the `init()` function of every file corresponding to a leaf in the tree of commands.

this issue is to write a pattern that makes specifying such a flag easier to implement and maintain _and_ to add the `--profile` flag described above.

**Comment by ransomw1c** [comment]
`--loglevel` is another flag that could be added in multiple places at once with such an impl

**Comment by ransomw1c** [comment]
auto-generating CLI documentation also factors into implementation decisions here.

**Comment by ransomw1c** [comment]
[hugo](https://github.com/gohugoio/hugo/blob/master/commands/commands.go) is an example of one extreme re. implementation decisions that this iss. might keep in mind:  that program builds its own api around the cobra library replete with builders/factories, etc.

for the time being, i'd like to find some middle ground between the current implementation and the sort of DSL-esque design of the hugo CLI.

**Comment by ransomw1c** [comment]
using cobra's `RunE` rather than the existing `log.fatal*()` calls is another ironing out tbd here.

**Comment by fredbi** [comment]
most inherited flags now use the `PersistentFlag` feature. Problem solved. Closing.
