### ISSUE TITLE
Options for upload of bundle on pod shutdown.

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#189]
The FUSE FS mount to create a new bundle needs to be shutdown and the upload complete when a Pod shuts down. This might be in the context of argo created pods. This issue is to investigate all options and formalize/implement the solutions.

**Comment by ransomw1c** [comment]
the current implementation does provide a way to notify the datamon mount process to unmount and start the upload (sending SIGINT to the process) as well as a way to determine if the upload completes (the process's exit status or its messages to standard out).

of course, there are other ways to go about implementing these requirements.  one method that'd been discussed (perhaps in relation to other tasks) is providing an interface to the process via filesystem operations, so the signal and status code mentioned above could be replaced by file writes and reads.

in particular, it'll be necessary investigate some specific details of what kubernetes Pod shutdown means.

**Comment by fredbi** [comment]
Ok so this done the way @ransomw1c has just described above and this demonstrably works.

The way to pass options & parameters to the sidecar is still a mess, though.

If we want to resume a sprint dealing with sidecar design/major changes in this protocol, I am all in: let's see that in separate issues/design documents.

Closing this
