### ISSUE TITLE
standard io selection 

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#192]
currently, the output of list and get commands (`repo list`, etc.) is sent to stderr rather than stdout.

this issue is to make a thorough-going over of which of the standard output channels is used to print various types of messages from the executable.

this issue could probably be re-named.

**Comment by ransomw1c** [comment]
upon addressing this iss., also remove the "Using config file" message.

**Comment by fredbi** [comment]
fixed with #375
