### ISSUE TITLE
good first issue for onboarding new contributors

### ISSUE THREAD

**Issue by chandresh-pancholi** [oneconcern/datamon#201]
Hi,

It would be great if you could create/map/tag issue for someone who wants to contribute. the tag can be a "good first issue".

**Comment by ransomw1c** [comment]
noticing that `KeysPrefix` is not implemented (i.e. is duct-typed, written to return an error) for some types of the `storage.Store` interface.

overall, although there is some limitation on bandwidth, we want to foster contributions in the long-term.

**Comment by fredbi** [comment]
Closing this, reducing noise.
