### ISSUE TITLE
RO FS FUSE dbg, perf

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#226]
there are various and sundry debuggings and performance improvements to the `bundle mount` command as used to mount a read-only bundle and stream from GCS:

- [ ] memory leaks on streaming read-only mount [1]
- [ ] memory usage during `core.populateFS()` [2]
- [ ] `populateFS` could be faster if parallelized [3]

`backup-filestore-output` and `1LqWPRbwaV6JXKIxJrYUrUV6ZIp` are a suitable repo and bundle to use for benchmarking.

**Comment by ransomw1c** [comment]
### additional notes

##### 1

move the benchmark bundle with `rsync` to duplicate this error

##### 2

there are several maps and/or radix trees attached to the read-only fs implementation struct.  some of these (e.g. `fsDir`) are only used during `populateFS`.  since these in-memory key-value stores are referenced by the implementation struct, they aren't GCed after `populateFS`.  hence, making members of the struct function-local variables will allow GC and reduce memory usage after `populateFS` returns.

### possible approaches

##### 1

consider `seekAhead` in `chunkReader.ReadAt()` in `cafs`.  particularly, the anonymous goroutine ought pass errors to an error channel.

review entire pathway from FUSE IOC to `(*Bundle).ReadAt()` (and perhaps elsewhere?) to `chunkReader.ReadAt`
.. are the bytes read counts correct? ..
.. is `copy(p[n:], buffer[offset:])` creating slices that aren't getting collected on loop iterations? ..
.. does removing _all_ `lru.Contains` usage matter? ..
.. and is there some synchronization issue with github.com/hashicorp/golang-lru usage?

##### 3

part and parcel of parallelization is further decomposition into simpler functions.

**Comment by ransomw1c** [comment]
monitoring memory use via `htop` during reads from the streaming read-only FUSE fs as in #227 show a bounded memory footprint according to the number of parallel processes (either `cp` or `rsync` reading bytes out of the filesystem).  in addition to the memory use after `populateFS`, additional memory scales according to number of processes like
* 10 : 8GiB
* 20 : 10GiB
* 40 : 11GiB
so there's more memory required to carry out more parallel reads, which is what we'd expect given that there's some buffering required for each read.  the non-linear growth of memory could be due to details of gcs or other upstream libraries.
particularly, the amount of memory required for parallel read operations does not continue to increase throughout the read:  it increases quickly and levels out at the indicated values.  it does not increase steadily thoughout the read, stopping at the indicated values.

**Comment by fredbi** [comment]
PR #368 did bring some significant effort toward fixing all the above-mentioned issues (essentially memory usage). Considering most of the above as solved.

 cafs/fuse pkgs might probably be improved further. Let's see if we can be more specific with issues & future improvements.
