### ISSUE TITLE
label direct lookup

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#231]
add a `label get` command that looks up bundle information by label.

the implementation details are distinct from piping `label list` to `grep` because directly accessing labels by name is different than filtering a list of labels:  labels are stored in a GCS bucket that allows directly access by a key that can be constructed from the label name.  so `label get` is going to be faster than filtering through all labels.

**Comment by ransomw1c** [comment]
if a label doesn't exist, exit with `syscall.ENOENT`

**Comment by fredbi** [comment]
this works now. Closing
