### ISSUE TITLE
postgres sidecar

### ISSUE THREAD

**Issue by ransomw1c** [oneconcern/datamon#256]
we have a sidecar-like use-case wherein the source and destination is a postgres database rather than datamon.  the task here to provide, either in the sidecar container or a different container, a user interface to make such an integration seamless with argo.

in particular, to store data to datamon, we have two use-cases for backup:
* backup selected tables from a database using `pg_dump`
* backup an entire database closer to the [fs level](https://www.postgresql.org/docs/11/backup-file.html)

the latter is not to be done exactly as in the linked documentation, because we can't guarantee that the database is vacuumed before the backup operation.  so we'll need some way (auxiliary program) to remove any sparseness when streaming the files out of the filesystem as well as any blocks that the db's b-tree has marked as invalid, hence a vendor-specific way.

restore is simpler, since the destination database will not contain conflicts:  it'll be necessary to take the artifact (possibly one of several types, suggesting a tagged union alike for the data within datamon's blob store) from datamon and add it to an empty postgres datadir.

**Comment by fredbi** [comment]
@ransomw1c 
> because we can't guarantee that the database is vacuumed before the backup operation. so we'll need some way (auxiliary program) to remove any sparseness when streaming the files out of the filesystem as well as any blocks that the db's b-tree has marked as invalid, hence a vendor-specific way.

with Postgres, this is carried out using the admin `CHECKPOINT` command under `psql`. See https://www.postgresql.org/docs/current/sql-checkpoint.html

**Comment by fredbi** [comment]
ok this is done now
