### ISSUE TITLE
Caching scheme

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#26]
Blobs for the CAFS should be cached. There are many aspects to caching that we need to decide
* In GKE is done via a disk attached to each node? Or is there a common caching disk that a daemon populates on request
* When are blobs kicked off from the cache?
   * Access time?

**Comment by fredbi** [comment]
@kerneltime  @ransomw1c  -- This is a github issue cleaning sweep
 
This story is now mostly done, at least for the mount RO story.
I am aware that our caching scheme is overall clunky and would benefit much from relying on some more solid KV store. My current thoughts go toward having badger db work as a local cache store.
