### ISSUE TITLE
Run to Bundle generation integration design

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#34]
At the end of a function run, output data needs to be written to a new bundle. There are some open questions we need to address
1. In a on going function what is the handshake to indicate a bundle is done
2. When creating the run.json where should the metadata for run come from
3. How is the output folder maintained.
This could be all done in the filter layer in the tubeless runtime that runs the functions. It can call the datamon cli create a new bundle, extract the metadata and move the output folder off to provide a fresh new output folder (or backup a snapshot of a DB if there is do data out folder)

**Comment by kerneltime** [comment]
Part of the over arching feature issue: https://github.com/oneconcern/datamon/issues/29

**Comment by fredbi** [comment]
@kerneltime @ransomw1c -- This is a github issue cleaning sweep

I am considering this done.
