### ISSUE TITLE
Implement the Merkel tree for a commit

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#45]
Each file is described as a hash but the entire set of file hashes needs to be hashed to effectively give a Merkel tree. This is to help calculate changes between commits.

**Comment by kerneltime** [comment]
This allows for quick detection of identical bundles but introduces complexity in terms of

- [ ] Choice of ordering of hashes

- [ ] Potential need to store all file hashes in memory or an alternative scheme to generate

- [ ] In the diamond workflow there will be additional complexity to generate this.

**Comment by fredbi** [comment]
@kerneltime @ransomw1c -- This is a github issue cleaning sweep

This is done. I noticed that there is a glitch in the node numbering of the last node whenever the file exactly matches n leaves. However unconventional, this works and is not blocking provided both reader and writer follow the same node numbering convention. Closing this now.
