### ISSUE TITLE
Live tracking of a branch

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#98]
While mounting a filesystem for a branch, if new bundles show up on the branch, the filesystem should auto refresh and pick up the latest.

**Comment by kerneltime** [comment]
This at a high level would entail.

FS:
1. Quiescing IO
2. Refreshing filesystem metadata and honoring old iNode ids
3. ..

K8S
1. A way to define the policy for the mount
2. Continuous checking or an event to trigger the refresh.

We need a spike to spec out and try the feature post integration of pipelines.

**Comment by fredbi** [comment]
As per previous discussions, branches are no more a feature we need, or even want to manage data sets. Closing this.
